# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ci

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build Godot Game
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: "index.html"
          preset: html5
          debugMode: "true"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - html5
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      
      - name: Publish to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ${{ github.workspace }}/${{ steps.build.outputs.build }}
          vercel-args: '--prod' #Optional
          
      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: godot-html5-test
          ITCH_USER: twopm
          PACKAGE: ${{ github.workspace }}/${{ steps.build.outputs.build }}

